# Mémoire du démon : compilation Compose gourmande, 30 Go dispo sur la machine.
org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
kotlin.mpp.applyDefaultHierarchyTemplate=false
gwsVersion=0.8.6
