package school.greenwood.plus.logic

import kotlin.random.Random

/** Le compteur reste au début de chaque variation, même lorsque tout est fait. */
object TitresDuJour {
    val textes: List<String> = listOf(
        "Le point du jour",
        "La page du jour",
        "Le cahier du jour",
        "Le carnet du jour",
        "Les notes du jour",
        "Le fil du jour",
        "Le repère du jour",
        "Le chapitre du jour",
        "Le rendez-vous du jour",
        "La parenthèse du jour",
        "Côté cahier",
        "Côté carnet",
        "Côté école",
        "Côté classe",
        "Côté leçons",
        "Côté devoirs",
        "Côté cartable",
        "Côté agenda",
        "Côté apprentissage",
        "Côté révisions",
        "Au fil du cahier",
        "Au fil du carnet",
        "Au fil des leçons",
        "Au fil des devoirs",
        "Au fil de l’école",
        "Au fil de la classe",
        "Au fil de l’agenda",
        "Au fil des pages",
        "Au fil des notes",
        "Au fil du cartable",
        "Le coin du cahier",
        "Le coin du carnet",
        "Le coin de l’école",
        "Le coin de la classe",
        "Le coin des leçons",
        "Le coin des devoirs",
        "Le coin du cartable",
        "Le coin de l’agenda",
        "Le coin des notes",
        "Le coin des révisions",
        "La pause cahier",
        "La pause carnet",
        "La pause école",
        "La pause leçons",
        "La pause devoirs",
        "La pause cartable",
        "La pause agenda",
        "La pause révisions",
        "La pause des pages",
        "La pause des notes",
        "La page des leçons",
        "La page des devoirs",
        "La page du cahier",
        "La page du carnet",
        "La page de l’école",
        "La page de la classe",
        "La page de l’agenda",
        "La page du cartable",
        "La page des notes",
        "La page des révisions",
        "Le cahier en lumière",
        "Le carnet en lumière",
        "L’école en lumière",
        "La classe en lumière",
        "Les leçons en lumière",
        "Les devoirs en lumière",
        "Le cartable en lumière",
        "L’agenda en lumière",
        "Les notes en lumière",
        "Les pages en lumière",
        "Un moment côté cahier",
        "Un moment côté carnet",
        "Un moment côté école",
        "Un moment côté classe",
        "Un moment côté leçons",
        "Un moment côté devoirs",
        "Un moment côté cartable",
        "Un moment côté agenda",
        "Un moment côté notes",
        "Un moment côté révisions",
        "Un œil sur le cahier",
        "Un œil sur le carnet",
        "Un œil sur les leçons",
        "Un œil sur les devoirs",
        "Un œil sur l’agenda",
        "Un œil sur les notes",
        "Un œil sur les pages",
        "Un œil sur le cartable",
        "Un œil sur la classe",
        "Un œil sur les révisions",
        "Le petit point cahier",
        "Le petit point carnet",
        "Le petit point école",
        "Le petit point classe",
        "Le petit point leçons",
        "Le petit point devoirs",
        "Le petit point cartable",
        "Le petit point agenda",
        "Le petit point notes",
        "Le petit point révisions",
    )

    fun titre(index: Int, restants: Int): String = "${CeSoir.compteur(restants)} · ${textes[index]}"

    /** Tirage uniforme parmi les autres titres, sans répétition immédiate. */
    fun suivant(actuel: Int, random: Random = Random.Default): Int =
        (actuel + 1 + random.nextInt(textes.size - 1)) % textes.size
}
