package school.greenwood.plus.logic

import kotlin.random.Random

/** Variations éditoriales du soir : aucun statut ni délai inventé. */
object TitresDuSoir {
    const val intervalleMillis = 12_000L

    val textes: List<String> = listOf(
        "Ce soir",
        "Le petit point du soir",
        "Le rendez-vous du soir",
        "Au fil de la soirée",
        "La page du soir",
        "Le cahier du soir",
        "Les notes du soir",
        "Le carnet du soir",
        "L’escale du soir",
        "La parenthèse du soir",
        "Le chapitre du soir",
        "Le temps du soir",
        "Le tableau du soir",
        "Le repère du soir",
        "Le regard du soir",
        "Le bilan de la soirée",
        "Le point de la soirée",
        "Le fil de la soirée",
        "Le coin de la soirée",
        "La pause de la soirée",
        "Une soirée, une page",
        "Le soir côté cahier",
        "Le soir côté école",
        "Le soir côté devoirs",
        "La soirée côté école",
        "La soirée côté cahier",
        "La soirée côté devoirs",
        "Notre page du soir",
        "Notre cahier du soir",
        "Notre carnet du soir",
        "Notre rendez-vous du soir",
        "Notre parenthèse du soir",
        "Notre petit point du soir",
        "Un regard sur le cahier",
        "Un regard sur les devoirs",
        "Un œil sur le cahier",
        "Un œil sur les devoirs",
        "Le cahier en lumière",
        "Le carnet en lumière",
        "Les devoirs en lumière",
        "Le cahier à la maison",
        "Le carnet à la maison",
        "L’école à la maison",
        "La classe à la maison",
        "Le coin des cahiers",
        "Le coin des devoirs",
        "Le coin du carnet",
        "Le coin de l’école",
        "Le coin des leçons",
        "La page des devoirs",
        "La page des leçons",
        "La page du cahier",
        "La page de l’école",
        "Le fil des devoirs",
        "Le fil des leçons",
        "Le fil du cahier",
        "Le fil de l’école",
        "Le point côté devoirs",
        "Le point côté leçons",
        "Le point côté cahier",
        "Le point côté école",
        "La pause cahier",
        "La pause carnet",
        "La pause devoirs",
        "La parenthèse cahier",
        "La parenthèse carnet",
        "La parenthèse devoirs",
        "L’escale cahier",
        "L’escale carnet",
        "L’escale devoirs",
        "Au fil du cahier",
        "Au fil du carnet",
        "Au fil des devoirs",
        "Au fil des leçons",
        "Côté cahier, ce soir",
        "Côté carnet, ce soir",
        "Côté école, ce soir",
        "Côté classe, ce soir",
        "Côté leçons, ce soir",
        "Côté devoirs, ce soir",
        "Le cahier de la soirée",
        "Le carnet de la soirée",
        "Les notes de la soirée",
        "Le chapitre de la soirée",
        "Le repère de la soirée",
        "La page de la soirée",
        "L’escale de la soirée",
        "La parenthèse du cahier",
        "La parenthèse de l’école",
        "Le rendez-vous du cahier",
        "Le rendez-vous des devoirs",
        "Le rendez-vous des leçons",
        "Un moment côté cahier",
        "Un moment côté carnet",
        "Un moment côté devoirs",
        "Un moment côté école",
        "Un instant côté cahier",
        "Un instant côté carnet",
        "Un instant côté devoirs",
        "Un instant côté école",
    )

    /** Tirage uniforme parmi les autres titres, sans répétition immédiate. */
    fun suivant(actuel: Int, random: Random = Random.Default): Int =
        (actuel + 1 + random.nextInt(textes.size - 1)) % textes.size
}
